### ISSUE TITLE
Running ThermoNeRF on other datasets

### ISSUE THREAD

**Issue by Neal2020GitHub** [Schindler-EPFL-Lab/thermo-nerf#15]
Hi authors! 

May I know how to preprocess other RGB and Thermal data to obtain the data structure like ThermoScenes. And then I am able to run ThermoNeRF on that data. 

Thank you.

**Comment by MalcolmMielle** [comment]
Hi! We are working on README that should clarify this. I'll edit this issue in a couple of day, thanks for bringing it up

**Comment by MalcolmMielle** [comment]
There is a documentation pushed in the thermoscenes package. See #16
