### ISSUE TITLE
I met the problem when build my own thermal scene

### ISSUE THREAD

**Issue by kevinycy** [Schindler-EPFL-Lab/thermo-nerf#23]
Hi authors!
When I build my own thermal scene, I met this problem. When i run COLMAP on the dataset i created with this code: python images_to_nerf_dataset.py --matching_method exhaustive --thermo-scene-data input2 --output-dir output2 --num-downscales 0 --update-colmap-json. I met the problem like this:
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'input2/rgb_eval_processed/frame_eval_00001.png' is not in the subpath of 'input2/rgb_train_processed' OR one path is relative and the other is absolute.

What should I do to handle that?

Thank you!
![the problem](https://github.com/user-attachments/assets/85432d20-96c8-441a-8678-80edbcd5dfb7)

**Comment by MalcolmMielle** [comment]
Does your version of nerfstudio include [this PR](https://github.com/nerfstudio-project/nerfstudio/pull/3396) by @jiaruiyu99 ? It seems like it was the same error and it was merged 2 months ago

**Comment by kevinycy** [comment]
Thank you! This change helped me solve the issue.
